export default function Head() {
  return (
    <>
      <title>Quadrico</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta name="developer" content="https://github.com/ChrisCoy"/>
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
